version: '3.9'

services:
  planner-db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"

